title: Katherine Horng
description: A portfolio of projects I have worked on
url: "" # your site URL when live, leave empty for local dev
baseurl: ""

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Top navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/

# Optional defaults for page layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true